services:
  postgres:
    image: postgres:17
    container_name: auth-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: auth
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d auth"]
      interval: 5s
      timeout: 5s
      retries: 5
  auth:
    build:
      context:  .
      dockerfile: Dockerfile.auth
    container_name: auth-service
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      APP_ENV: local
      HTTP_PORT: 8080
      DATABASE_URL: postgres://postgres:postgres@postgres:5432/auth?sslmode=disable
      JWT_SECRET: super-secret-key
      TOKEN_TTL: 1h
    ports:
      - "8080:8080"

  migrator:
    build:
      context:  .
      dockerfile: Dockerfile.auth
    container_name: auth-migrator
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      APP_ENV: local
      HTTP_PORT: 8080
      DATABASE_URL: postgres://postgres:postgres@postgres:5432/auth?sslmode=disable
      JWT_SECRET: super-secret-key
      TOKEN_TTL: 1h
    command: ["go", "run", "cmd/migrator/main.go"]

  articles:
    build:
      context:  .
      dockerfile: Dockerfile.articles
    container_name: articles-service
    depends_on:
      postgres:
        condition: service_healthy
      notification:
        condition: service_started
    environment:
      APP_ENV: local
      ARTICLES_HTTP_PORT: 8081
      DATABASE_URL: postgres://postgres:postgres@postgres:5432/auth?sslmode=disable
      JWT_SECRET: super-secret-key
      TOKEN_TTL: 1h
      NOTIFICATION_BASE_URL: http://notification:8082
    ports:
      - "8081:8081"

  notification:
    build:
      context: .
      dockerfile: Dockerfile.notification
    container_name: notification-service
    environment:
      APP_ENV: local
      NOTIFICATION_HTTP_PORT: 8082
    ports:
      - "8082:8082"

  

volumes:
  postgres_data:

